# Generated by Django 4.0.1 on 2022-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumb',
            name='img',
        ),
        migrations.AddField(
            model_name='thumb',
            name='img_url',
            field=models.CharField(default='bruh', max_length=200),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
