# Generated by Django 4.0.1 on 2022-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_thumb_img_thumb_img_url_alter_thumb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thumb',
            name='title',
            field=models.CharField(default='no title', max_length=200),
        ),
    ]
