# Generated by Django 4.0.1 on 2022-01-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_thumb_rating_alter_thumb_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumb',
            name='title',
        ),
    ]
