# Generated by Django 4.0.1 on 2022-01-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_thumb_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='img_url',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
