# Generated by Django 4.0.1 on 2022-01-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_thumb_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumb',
            name='title',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
